#!/bin/bash

set -e

# Skip Go installation in CI - already provided by actions/setup-go
if [ -z "$GITHUB_ACTIONS" ]; then
    . script/ensure-go-installed
fi

set -x
if [ ! -L .gopath/src/github.com/github/gh-ost ]; then
    rm -rf .gopath
    mkdir -p .gopath/src/github.com/github
    ln -s "$PWD" .gopath/src/github.com/github/gh-ost
fi
export GOPATH=$PWD/.gopath:$GOPATH
